### ISSUE TITLE
in Fidel.openForm after error message "card already linked"

### ISSUE THREAD

**Issue by jahskee** [FidelLimited/rn-sdk#13]
After "card already linked" error message, I tried to enter a non linked test cc.
The card was added but the "metadata" or custom fields in the object is already empty after 2nd successful attempt.

**Comment by c0derabbit** [comment]
Hey, we'll look at this soon.

**Comment by jahskee** [comment]
I tried this work-around, in the exception block, I again reset the Fidel options to make it work.

**Comment by mishoboss** [comment]
I can confirm this issue! The "metaData" property becomes empty after some error occurs.

**Comment by c0derabbit** [comment]
yeah this was an issue related to iOS that has been recently fixed. 
https://releasenotes.fidel.uk/ios-sdk-v-1-6-1-127954

@ccorneliu can we release a version of RN please that includes the above fix?

**Comment by ccorneliu** [comment]
@c0derabbit @mishoboss @jahskee No need to push another RN library version for this one. The RN library it's just a bridge to the iOS SDK. Just update the Fidel Cocoapods dependency in your project with `pod update Fidel`. This should fix it. Make sure you install the latest version (right now the latest version is `1.6.1`)

**Comment by c0derabbit** [comment]
@mishoboss @jahskee closing this in that case, please let us know if the issue persists after pod update.
