### ISSUE TITLE
Doesn't work with expo-unimodules or iOS platform 10.0, RCTAnimation issues

### ISSUE THREAD

**Issue by c0derabbit** [FidelLimited/rn-sdk#16]
Turns out it actually was a few separate issues. Basically, I am using the Expo bare workflow to quickstart my project, and this causes the podfile to default to platform: 10.0, which Fidel doesn't like, but instead wants 9.1. If you set the podfile to 9.1, you cannot use Expo's bare workflow, which has several packages that require platform 10.0

_Originally posted by @JustinRohweller in https://github.com/FidelLimited/rn-sdk/issues/11#issuecomment-527674001_

**Comment by JustinRohweller** [comment]
I would change the title to be expo-unimodules, not just Expo, since it is a native package, it is implied that it won't work with standard Expo

**Comment by JustinRohweller** [comment]
Steps to reproduce: Expo init Fidelproject
Install Fidel following instructions
Run project, will not build

**Comment by ccorneliu** [comment]
That’s weird. It should work with the platform set to 10.0. I will check what happens.

@JustinRohweller, can you please clarify what "Fidel doesn't like" means? What happens more precisely? You receive an error when you run `pod install`?

**Comment by JustinRohweller** [comment]
If you follow my steps to reproduce above, pod install succeeds, but I get RCTAnimation errors, if I fix those I get more build errors within Fidel's project.
If you try to go the other way, and start with a vanilla react native project, add Fidel, then add react-native-unimodules, I get an error in pod install that unimodules requires platform 10.0.

**Comment by ccorneliu** [comment]
Hi, @JustinRohweller @JonathonJulian ! I got this fixed now. It should also work with RN >= 0.6 now. Please check the newest released version of the Fidel library: 1.2.0 and also the Automatic linking instructions. Integrating the Fidel RN library with Cocoapods might be more convenient.

Thank you for your patience.

**Comment by JonathonJulian** [comment]
great, thank you just confirmed its working for us now. also fyi it worked while keeping the platform at 10. contrary to the doc update
appreciate getting this working
cheers!
