### ISSUE TITLE
couldn't find key uri in dynamic object (Android)

### ISSUE THREAD

**Issue by Jendyy** [FidelLimited/rn-sdk#19]
**react-native: 0.50.4
fidel-react-native: 1.0.5**

on ios it works!

on android error loading application:

<img width="214" alt="Screenshot 2019-09-24 at 20 22 24" src="https://user-images.githubusercontent.com/50834021/65534932-15813600-df09-11e9-9d0c-445f4791d227.png">

**MainApplication.java:**
import com.fidelreactlibrary.FidelPackage
...
new FidelPackage(),
...

**android/app/build.gradle:**
...
compile project(':fidel-react-native')
...

**android/build.gradl:e**
allprojects {
    repositories {
        maven { url "https://www.jitpack.io" }
...

**android/settings.gradle:**
...
include ':fidel-react-native'
project(':fidel-react-native').projectDir = new File(rootProject.projectDir,'../node_modules/fidel-react-native/android')
...

**App.js:**
...
import Fidel from "fidel-react-native";
...
Fidel.setup({
  apiKey:'pk_live_...',
  programId: '...'
})

android build successfully but the application error:

**couldn't find key uri in dynamic object**

What could be wrong?

**Comment by ccorneliu** [comment]
Hi @Jendyy,

I can check what's happening. Did you also set any options with `Fidel.setOptions({ ... })`? Can you paste that code, please as well? Seems like an error when trying to use the `bannerImage` option.

Please make sure that you resolve your `bannerImage` before setting it. You can check an example here: https://github.com/FidelLimited/rn-sdk#how-to-use-fidels-react-native-sdk

Please let me know, if this was the issue so that we can improve the SDK and maybe handle this more gracefully.

Thank you!

**Comment by Jendyy** [comment]
> Hi @ccorneliu ! Thank you, problem solved!

That was my fault. The error was due to {} 

before:
Fidel.setOptions ({
  bannerImage: { logoInverseWhite },

after:
 Fidel.setOptions ({
  bannerImage: logoInverseWhite,

**but now there is a new problem**
<img width="223" alt="Screenshot 2019-09-25 at 11 45 41" src="https://user-images.githubusercontent.com/50834021/65584746-08f0f200-df8a-11e9-92d5-e95975f8fe5a.png">

my fidel options:

const cardSchemes = new Set([
  Fidel.CardScheme.visa,
  Fidel.CardScheme.mastercard,
  Fidel.CardScheme.americanExpress
]);

Fidel.setOptions ({
  bannerImage: logoInverseWhite,
  country: Fidel.Country.unitedKingdom,
  supportedCardSchemes: Array.from(cardSchemes),
  autoScan: false,
  // metaData: {'meta-data-1': 'value1'}, //additional data to pass with the card
  companyName: 'My RN Company',
  deleteInstructions: 'by contacting our support team at privacy@example.com',
  privacyUrl: 'https://fidel.uk',
});
