### ISSUE TITLE
Feature Request: Bilingual language support for Canada

### ISSUE THREAD

**Issue by JonathonJulian** [FidelLimited/rn-sdk#20]
Hello,

We require both english and french text based on device locale when country is set to Canada. Currently it shows only english.

**Comment by ccorneliu** [comment]
Hi,

We're implementing localization in the next couple of weeks :). We'll keep in mind Canadian English and French users.

**Comment by JonathonJulian** [comment]
hi, has there been any progress with this?

**Comment by c0derabbit** [comment]
hey @JonathonJulian ETA is late this week or early next week, we'll keep you posted!

**Comment by ccorneliu** [comment]
Hello, @JonathonJulian ! This has been pushed in the newest release.
