### ISSUE TITLE
Failure building in android because of private jitpack repository

### ISSUE THREAD

**Issue by Quilamir** [FidelLimited/rn-sdk#21]
after successfully integrating the sdk into our project a few days ago and actually testing it in our react-native application for some reason we are no longer able to build the android version with the following error:

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:mergeDebugAssets'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.github.FidelLimited:android-sdk:1.3.3.
     Required by:
         project :app > project :fidel-react-native
      > Could not resolve com.github.FidelLimited:android-sdk:1.3.3.
         > Could not get resource 'https://jitpack.io/com/github/FidelLimited/android-sdk/1.3.3/android-sdk-1.3.3.pom'.
            > Could not GET 'https://jitpack.io/com/github/FidelLimited/android-sdk/1.3.3/android-sdk-1.3.3.pom'.
               > Read timed out
   > Could not resolve com.github.wix-playground:ahbottomnavigation:3.0.2.
     Required by:
         project :app > project :react-native-navigation
      > Skipped due to earlier error
```

the error is happening on several developer's machines both mac and windows.

when trying to access the url of the sdk directly the response is ```Repo not found or no token provided```

any ideas why this is happening?

**Comment by Quilamir** [comment]
I have attempted adding credentials to the maven setup as well and still getting the same error

**Comment by ccorneliu** [comment]
@Quilamir Can you please try to clean the project (Build -> Clean project) and then invalidate caches (File -> Invalidate Caches / Restart)?

Did you try to downgrade the SDK to version 1.3.0? There is a new version: 1.3.3. Please use the latest to make sure you don't encounter any other issues that we fixed in later versions.

When I downgraded from 1.3.3 I encountered the same issue as you did. After cleaning the project and invalidating caches, Gradle resolved the older Fidel library (1.3.0). However, I recommend that you use the latest version: 1.3.3.

**Comment by Quilamir** [comment]
@ccorneliu we are using the react native package, the version used is determined by the package that was released by Fidel.

the version used is 1.3.3 as shown in the error log in the OP.

I will attempt to clear caches though i am not sure how this will help as the problem is access in jitpack to download the 1.3.3 version

**Comment by Quilamir** [comment]
today it seems like things are back to normal, we can build the application again with no changes needed on our end.
i am assuming the repository has been made public again.

**Comment by mishoboss** [comment]
This seems to be an issue again. What's the solution anyways? Where and what kind of credentials need to be set?

**Comment by ccorneliu** [comment]
@mishoboss I think this time it was a temporary issue we had on our end. Please try again to sync with gradle. Also, please make sure the configuration was done correctly as indicated in the README.

**Comment by mishoboss** [comment]
Hi guys, same issue. :) Maybe it's on your end again?

**Comment by ccorneliu** [comment]
Hi @mishoboss ! Very likely it's on our end again. Sorry about that. I will reply when I get more news.
