### ISSUE TITLE
Request for Feature: Allow for complete overwrite of the privacy policy information.

### ISSUE THREAD

**Issue by JustinRohweller** [FidelLimited/rn-sdk#24]
The Fidel SDK only allows for you to modify the privacy policy link, and the delete instructions.
Our app in particular has the need for being able to change the entire message in order to meet Visa's requirements.
Hopefully would be as simple as having a new prop like: overwrittenPrivacyPolicyDescription.
Thanks

**Comment by c0derabbit** [comment]
Hi @JustinRohweller, thanks for raising this! We are discussing this topic internally as we speak, and we'll come up with a solution soon.

**Comment by JustinRohweller** [comment]
Hey @c0derabbit , any news? Just checking in.

**Comment by c0derabbit** [comment]
hey @JustinRohweller sure, we're looking to release a new version with NA-specific terms towards the end of this week or beginning of next. I'll keep you posted.

**Comment by ccorneliu** [comment]
Hello, @JustinRohweller. This has been done in the latest release (1.3.0). Please make sure that after you update the Fidel RN library, you also update the Cocoapods library. Fidel's latest iOS library that you should get is 1.8.1 (or higher, depending on when you'll update it).
