### ISSUE TITLE
Android: Country is defaulting to UK

### ISSUE THREAD

**Issue by JonathonJulian** [FidelLimited/rn-sdk#25]
Hi,
we have set  `country: Fidel.Country.canada` in `Fidel.setOptions` but in the app it still defaults to UK. is there a workaround to set this in android?

**Comment by ccorneliu** [comment]
Hi @JonathonJulian,

I tried different setup combinations and tried o replicate this, but I couldn't. Can you please provide more information about your context and share more detailed Fidel SDK setup code? (without any of your private information, of course)

Please make sure that you're using the latest versions. If you're using the latest React Native library (version `1.2.2` right now), then you should have the Android Fidel SDK installed at version `1.3.3`. That one should work fine.

**Comment by ccorneliu** [comment]
Do you still have this issue, @JonathonJulian ? I will close it, for now. Please let me know if I should reopen the issue.
