### ISSUE TITLE
Dependency resolution error

### ISSUE THREAD

**Issue by gduffy8** [FidelLimited/rn-sdk#26]
Hi, 

Getting dependency resolution error on build for React Native SDK between modules **annotations-13.0.jar** (org.jetbrains:annotations:13.0) and **annotations-java5-15.0.jar** (org.jetbrains:annotations-java5:15.0)

Version Info:
"fidel-react-native": "^1.2.2",
"react-native": "0.61.5"

`Duplicate class org.intellij.lang.annotations.Flow found in modules annotations-13.0.jar (org.jetbrains:annotations:13.0) and annotations-java5-15.0.jar (org.jetbrains:annotations-java5:15.0)
Duplicate class org.intellij.lang.annotations.Identifier found in modules annotations-13.0.jar (org.jetbrains:annotations:13.0) and annotations-java5-15.0.jar (org.jetbrains:annotations-java5:15.0)
Duplicate class org.intellij.lang.annotations.JdkConstants found in modules annotations-13.0.jar (org.jetbrains:annotations:13.0) and annotations-java5-15.0.jar (org.jetbrains:annotations-java5:15.0)
Duplicate class org.intellij.lang.annotations.JdkConstants$AdjustableOrientation found in modules annotations-13.0.jar (org.jetbrains:annotations:13.0) and annotations-java5-15.0.jar (org.jetbrains:annotations-java5:15.0)
Duplicate class org.intellij.lang.annotations.JdkConstants$BoxLayoutAxis found in modules annotations-13.0.jar (org.jetbrains:annotations:13.0) and annotations-java5-15.0.jar (org.jetbrains:annotations-java5:15.0)
Duplicate class org.intellij.lang.annotations.JdkConstants$CalendarMonth found in modules annotations-13.0.jar (org.jetbrains:annotations:13.0) and annotations-java5-15.0.jar (org.jetbrains:annotations-java5:15.0)
Duplicate class org.intellij.lang.annotations.JdkConstants$CursorType found in modules annotations-13.0.jar (org.jetbrains:annotations:13.0) and annotations-java5-15.0.jar (org.jetbrains:annotations-java5:15.0)
Duplicate class org.intellij.lang.annotations.JdkConstants$FlowLayoutAlignment found in modules annotations-13.0.jar (org.jetbrains:annotations:13.0) and annotations-java5-15.0.jar (org.jetbrains:annotations-java5:15.0)
Duplicate class org.intellij.lang.annotations.JdkConstants$FontStyle found in modules annotations-13.0.jar (org.jetbrains:annotations:13.0) and annotations-java5-15.0.jar (org.jetbrains:annotations-java5:15.0)
Duplicate class org.intellij.lang.annotations.JdkConstants$HorizontalAlignment found in modules annotations-13.0.jar (org.jetbrains:annotations:13.0) and annotations-java5-15.0.jar (org.jetbrains:annotations-java5:15.0)
Duplicate class org.intellij.lang.annotations.JdkConstants$InputEventMask found in modules annotations-13.0.jar (org.jetbrains:annotations:13.0) and annotations-java5-15.0.jar (org.jetbrains:annotations-java5:15.0)
Duplicate class org.intellij.lang.annotations.JdkConstants$ListSelectionMode found in modules annotations-13.0.jar (org.jetbrains:annotations:13.0) and annotations-java5-15.0.jar (org.jetbrains:annotations-java5:15.0)
Duplicate class org.intellij.lang.annotations.JdkConstants$PatternFlags found in modules annotations-13.0.jar (org.jetbrains:annotations:13.0) and annotations-java5-15.0.jar (org.jetbrains:annotations-java5:15.0)
Duplicate class org.intellij.lang.annotations.JdkConstants$TabLayoutPolicy found in modules annotations-13.0.jar (org.jetbrains:annotations:13.0) and annotations-java5-15.0.jar (org.jetbrains:annotations-java5:15.0)
Duplicate class org.intellij.lang.annotations.JdkConstants$TabPlacement found in modules annotations-13.0.jar (org.jetbrains:annotations:13.0) and annotations-java5-15.0.jar (org.jetbrains:annotations-java5:15.0)
Duplicate class org.intellij.lang.annotations.JdkConstants$TitledBorderJustification found in modules annotations-13.0.jar (org.jetbrains:annotations:13.0) and annotations-java5-15.0.jar (org.jetbrains:annotations-java5:15.0)
Duplicate class org.intellij.lang.annotations.JdkConstants$TitledBorderTitlePosition found in modules annotations-13.0.jar (org.jetbrains:annotations:13.0) and annotations-java5-15.0.jar (org.jetbrains:annotations-java5:15.0)
Duplicate class org.intellij.lang.annotations.JdkConstants$TreeSelectionMode found in modules annotations-13.0.jar (org.jetbrains:annotations:13.0) and annotations-java5-15.0.jar (org.jetbrains:annotations-java5:15.0)
Duplicate class org.intellij.lang.annotations.Language found in modules annotations-13.0.jar (org.jetbrains:annotations:13.0) and annotations-java5-15.0.jar (org.jetbrains:annotations-java5:15.0)
Duplicate class org.intellij.lang.annotations.MagicConstant found in modules annotations-13.0.jar (org.jetbrains:annotations:13.0) and annotations-java5-15.0.jar (org.jetbrains:annotations-java5:15.0)
Duplicate class org.intellij.lang.annotations.Pattern found in modules annotations-13.0.jar (org.jetbrains:annotations:13.0) and annotations-java5-15.0.jar (org.jetbrains:annotations-java5:15.0)
Duplicate class org.intellij.lang.annotations.PrintFormat found in modules annotations-13.0.jar (org.jetbrains:annotations:13.0) and annotations-java5-15.0.jar (org.jetbrains:annotations-java5:15.0)
Duplicate class org.intellij.lang.annotations.PrintFormatPattern found in modules annotations-13.0.jar (org.jetbrains:annotations:13.0) and annotations-java5-15.0.jar (org.jetbrains:annotations-java5:15.0)
Duplicate class org.intellij.lang.annotations.RegExp found in modules annotations-13.0.jar (org.jetbrains:annotations:13.0) and annotations-java5-15.0.jar (org.jetbrains:annotations-java5:15.0)
Duplicate class org.intellij.lang.annotations.Subst found in modules annotations-13.0.jar (org.jetbrains:annotations:13.0) and annotations-java5-15.0.jar (org.jetbrains:annotations-java5:15.0)
Duplicate class org.jetbrains.annotations.Contract found in modules annotations-13.0.jar (org.jetbrains:annotations:13.0) and annotations-java5-15.0.jar (org.jetbrains:annotations-java5:15.0)
Duplicate class org.jetbrains.annotations.Nls found in modules annotations-13.0.jar (org.jetbrains:annotations:13.0) and annotations-java5-15.0.jar (org.jetbrains:annotations-java5:15.0)
Duplicate class org.jetbrains.annotations.NonNls found in modules annotations-13.0.jar (org.jetbrains:annotations:13.0) and annotations-java5-15.0.jar (org.jetbrains:annotations-java5:15.0)
Duplicate class org.jetbrains.annotations.NotNull found in modules annotations-13.0.jar (org.jetbrains:annotations:13.0) and annotations-java5-15.0.jar (org.jetbrains:annotations-java5:15.0)
Duplicate class org.jetbrains.annotations.Nullable found in modules annotations-13.0.jar (org.jetbrains:annotations:13.0) and annotations-java5-15.0.jar (org.jetbrains:annotations-java5:15.0)
Duplicate class org.jetbrains.annotations.PropertyKey found in modules annotations-13.0.jar (org.jetbrains:annotations:13.0) and annotations-java5-15.0.jar (org.jetbrains:annotations-java5:15.0)
Duplicate class org.jetbrains.annotations.TestOnly found in modules annotations-13.0.jar (org.jetbrains:annotations:13.0) and annotations-java5-15.0.jar (org.jetbrains:annotations-java5:15.0)
Go to the documentation to learn how to Fix dependency resolution errors.`

**Comment by ccorneliu** [comment]
Hi @gduffy8,

Can you please share a more complete list of dependencies/libraries that you used in your React Native app? Also, if you added Android dependencies manually (without npm or yarn), please share those as well. Just trying to replicate the problem, so that if I push a fix I will be sure that it will solve the problem.

Thanks a lot!

**Comment by gduffy8** [comment]
Sure, attached is my package.json (in txt format) file. I don't believe any were added manually. I can retrieve app dependency list if that helps?

[package.txt](https://github.com/FidelLimited/rn-sdk/files/4321440/package.txt)

**Comment by ccorneliu** [comment]
@gduffy8 Thanks a lot. Found the issue. Will push an update by Monday :).

**Comment by gduffy8** [comment]
That's great, I'll check it out tomorrow

**Comment by ccorneliu** [comment]
@gduffy8 Sure thing. Please use version 1.2.3 of the React Native SDK. It should fix the issue. Please make sure that you clean any cache of the Android project before testing.

**Comment by gduffy8** [comment]
Got past that build error now but getting country related error. I have it set in my setOptions method



    Fidel.setup({
      apiKey: testingConfiguration.fidel_api_key,
      programId: testingConfiguration.fidel_program_id,
    });

    Fidel.setOptions({
      bannerImage: resolvedImage,
      country: Fidel.Country.ireland,
      supportedCardSchemes: Array.from(cardSchemes),
      autoScan: false,
      metaData: {oid: (tokenData && tokenData.oid) || ''},
      deleteInstructions: 'My custom delete instructions!',
      privacyUrl: 'https://fidel.uk',
    });`

![image](https://user-images.githubusercontent.com/49955178/76784300-48ff9780-67ab-11ea-85ad-bc5b0ebdb27e.png)

**Comment by gduffy8** [comment]
@ccorneliu Do you want me to create a new issue here for this? Any ideas? I have also tried setting country to Fidel.Country.IRELAND but same issue.

**Comment by ccorneliu** [comment]
No need @gduffy8 . I'll check this tomorrow morning.

**Comment by gduffy8** [comment]
Thanks @ccorneliu Let me know if you need anything and I will supply asap. Hoping to get this SDK integrated soon

**Comment by gduffy8** [comment]
Not sure what happened here @ccorneliu I must have had some corrupted files in my repo. I started from a fresh repo and all appears to be working correctly now. However, I setup Fidel for Ireland only on Android, yet all countries are being displayed within Link. Any ideas on that?

**Comment by ccorneliu** [comment]
@gduffy8 I can't reproduce this behavior.  I tried multiple times. Does this still happen for you? Please make sure that you re-build and re-run your react native app after changing your configuration. Also, please note that the country names are lowercase, so if you wrote `Fidel.Country.Ireland` it will not work. The correct value is: `Fidel.Country.ireland` (with a lowercase "i").

**Comment by gduffy8** [comment]
Cleaning and rebuilding has done the trick. Thanks for your help, this can
be closed
