### ISSUE TITLE
Example Proj - not working, Error: Library not loaded: @rpath/libswiftCore.dylib

### ISSUE THREAD

**Issue by jahskee** [FidelLimited/rn-sdk#3]
XCode 10.1

I tried running the example, it did not work instead it shows the error below

dyld: Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: /Users/mac/Library/Developer/CoreSimulator/Devices/7D34A292-2F22-46AB-BE72-4F2743ACED3A/data/Containers/Bundle/Application/EA16E81F-A8CD-4DB5-A6DF-C9C1186C32F0/example.app/Frameworks/Fidel.framework/Fidel
  Reason: image not found
(lldb)

**Comment by jahskee** [comment]
This was fixed by using react-native-swift then further configuration of  RN Project was made.


- pod 'Fidel', '~>1.4.5'
- project must be set to use swift 4.2

The configuration in IOS also applies to RN IOS.

**Comment by c0derabbit** [comment]
Hey, thanks for the detailed info! We'll try to make this a bit smoother.

**Comment by ccorneliu** [comment]
Will check this to understand what could've happened, but usually, we got this error message appears when `Always Embed Swift Standard Libraries` flag is set to `NO`. It should be set to `YES`. I'll try different configurations.

**Comment by jahskee** [comment]
Thank you!
