### ISSUE TITLE
Can't Link Canadian Cards

### ISSUE THREAD

**Issue by JustinRohweller** [FidelLimited/rn-sdk#36]
I always get the error code:
```{"errorCode": "missing_mandatory_info", "message": "You have set a North American default country or you allow the user to select a North American country. For North American countries it is mandatory for you to provide the Terms and Conditions URL."}```
#
```
const cardSchemes = new Set([
      Fidel.CardScheme.visa,
      Fidel.CardScheme.mastercard,
      Fidel.CardScheme.americanExpress
    ]);
    Fidel.setOptions({
      // bannerImage: resolvedImage,
      country: Fidel.Country.canada,
      supportedCardSchemes: Array.from(cardSchemes),
      autoScan: false,
      metaData: { uid: currentUser.uid },
      companyName: "Lynq",
      deleteInstructions: "emailing Lynq at support@lynq.cash",
      privacyUrl: "https://fidel.uk",
      termsConditionsURL: 'https://lynq.cash/privacy-policy/',
      programName: "Lynq Cash Rewards"
    });
```

**Comment by JustinRohweller** [comment]
Version 1.3.0

**Comment by JustinRohweller** [comment]
It works perfectly fine for other countries (non-North American).

**Comment by JustinRohweller** [comment]
I am fairly confident that the logic for making sure the options have a termsConditionsURL is just off.
Please take a look when you get a chance. Thanks

**Comment by JustinRohweller** [comment]
Lastly, I did just want to say thanks for the quick turnaround time on the prior issue.

**Comment by ccorneliu** [comment]
Hey, @JustinRohweller! I'm sorry. I made a typo in the documentation. The terms and conditions URL key should be: `termsConditionsUrl`, not `termsConditionsURL`. I fixed this in the documentation now too.
