### ISSUE TITLE
Fidel causes build failure on Release IOS 14 build

### ISSUE THREAD

**Issue by JustinRohweller** [FidelLimited/rn-sdk#42]
I installed Fidel according to the instructions, and it runs perfectly fine on debug builds, but on the release build it crashes app with:

```.../fidel-react-native/ios/FLRNSetupAdapter.m:35:5: Use of undeclared identifier 'FLFidel'```
and
```.../fidel-react-native/ios/FLRNSetupAdapter.m:36:5: Use of undeclared identifier 'FLFidel' ```

I have pod 'fidel-react-native', :path => '../node_modules/fidel-react-native' in my podfile, I have platform :ios, '9.1' in my podfile as well.

```"fidel-react-native": "^1.3.0",``` in my package.json
React Native version: 0.61.5
Will look to test it with a blank project as well.

Thanks again for your help.

**Comment by JustinRohweller** [comment]
Was able to reproduce the same? (similar) issue with a brand new project. Admittedly a different react-native version. (0.63.2)
Steps to reproduce:
```npx react-native init TestFidel```
```yarn add fidel-react-native```
For me I didn't see pod 'fidel-react-native', :path => '../node_modules/fidel-react-native' in my podfile, so I did npx react-native link fidel-react-native.
```cd ios```
```pod install```
Run with debug scheme. Works fine.
Run with release scheme. Build fails with:
```/Users/justin/Documents/TestFidel/node_modules/fidel-react-native/ios/FLRNOptionsAdapter.m:17:9: In file included from /Users/justin/Documents/TestFidel/node_modules/fidel-react-native/ios/FLRNOptionsAdapter.m:17:```
And just says that for every instance of FLFidel.
Would not be surprised if fixing that issue also fixes the same one I have described above as well.

**Comment by ccorneliu** [comment]
@JustinRohweller Will look into this issue today. I'll get back to you with the results ASAP.

**Comment by JustinRohweller** [comment]
Thanks man

**Comment by ccorneliu** [comment]
@JustinRohweller It seems like it's a problem with the Objective-C headers generated by Xcode, for the native framework (which is imported with Cocoapods). I will need to fix that in some way. I will have more news tomorrow afternoon.

**Comment by ccorneliu** [comment]
@JustinRohweller Can you please confirm that this fails only for iOS simulators? When you build with the release scheme on a **real device** does it work? I would expect that it does work on your real device, but not when you run with the release scheme on the new XCode 12 Simulators.

**Comment by JustinRohweller** [comment]
Hey @ccorneliu , Thanks again for looking into this.
Confirmed that it fails only for iOS simulators. The release build works successfully on Testflight (real iOS devices).
Unfortunately, adding arm64 to excluded architectures for the release build still did not work.
Got the same error.
Either way, good to know I can confidently ignore it.

<img width="1792" alt="Screen Shot 2020-09-30 at 2 42 11 PM" src="https://user-images.githubusercontent.com/25038150/94742951-64875580-032b-11eb-87e2-563cb45b545c.png">

**Comment by gjhughes** [comment]
Hey @ccorneliu just wondered if there was any progress on this as we are running into the same issue?

**Comment by ccorneliu** [comment]
@gjhughes I am still looking into this. Sorry about this. There are even differences between Xcode 12.0 and 12.0.1. Just to be sure, on your end you can build the app on a real device, right? (but not on simulators)

**Comment by gjhughes** [comment]
@ccorneliu no problem.  Yeah, release builds seem to be fine, the issue was actually while generating builds for our e2e tests with detox.  Passing `ONLY_ACTIVE_ARCH=YES` to the build script fixes it for now.

**Comment by ccorneliu** [comment]
By updating with Cocoapods to the latest Fidel iOS SDK version (1.8.2), Cocoapods will add the correct build settings. We just excluded the arm64 architecture for simulators, for now.

Please run `pod update Fidel` and make sure you install version `1.8.2`. This should allow your projects to build fine on Simulators as well.

Please feel free to reopen this issue if you encounter this problem again. I'll do my best to fix it.

**Comment by JonathonJulian** [comment]
Hello we are still experiencing this issue..

Using Xcode CLI 12.4 on MacOs 11.2.3 (M1)
node version 1.4.0
native version 1.8.2
arm64 is showing as excluded
![Screen Shot 2021-04-21 at 2 46 08 PM](https://user-images.githubusercontent.com/15183881/115625357-cea81d80-a2b0-11eb-8b9e-bd98091c9047.png)

![Screen Shot 2021-04-21 at 2 46 22 PM](https://user-images.githubusercontent.com/15183881/115625349-ca7c0000-a2b0-11eb-9958-8f0ec49067bf.png)
