### ISSUE TITLE
Test credit cards are invalid

### ISSUE THREAD

**Issue by jahskee** [FidelLimited/rn-sdk#5]
I tried to use the test cc posted in Fidel doc, but it returns an invalid error.
Please advise.

-Jaizon

**Comment by c0derabbit** [comment]
hi @jahskee, could you please provide some more info? what test card number did you try?

**Comment by jahskee** [comment]
Hi c0derabbit,

The test cc # and exp mm/yy was marked red.
 
![testCCIssue](https://user-images.githubusercontent.com/10620946/61750360-31ceee00-ad73-11e9-888f-428063c6df73.png)

**Comment by c0derabbit** [comment]
I can't reproduce, there must be something other than the ccn that causes the whole form to appear as invalid. We'll try to investigate this.

**Comment by c0derabbit** [comment]
@jahskee I've found some inconsistencies in Android. A quick look suggests that we might be Luhn checking test card numbers. I'll verify and be back!

**Comment by c0derabbit** [comment]
@ccorneliu this looks like something in the native SDKs. Can you please check card validation there, and whether we correctly determine test / live environment?

**Comment by jahskee** [comment]
Looks like, I don't see this issue anymore.

**Comment by c0derabbit** [comment]
Me neither. Closing as most probably solved in 1.1.0.
