### ISSUE TITLE
Hello we are still experiencing this issue..

### ISSUE THREAD

**Issue by JonathonJulian** [FidelLimited/rn-sdk#55]
Hello we are still experiencing this issue..

Using Xcode CLI 12.4 on MacOs 11.2.3 (M1)
node version 1.4.0
native version 1.8.2
arm64 is showing as excluded
![Screen Shot 2021-04-21 at 2 46 08 PM](https://user-images.githubusercontent.com/15183881/115625357-cea81d80-a2b0-11eb-8b9e-bd98091c9047.png)

![Screen Shot 2021-04-21 at 2 46 22 PM](https://user-images.githubusercontent.com/15183881/115625349-ca7c0000-a2b0-11eb-9958-8f0ec49067bf.png)

_Originally posted by @JonathonJulian in https://github.com/FidelLimited/rn-sdk/issues/42#issuecomment-824381024_

**Comment by ccorneliu** [comment]
Hi @JonathonJulian ,

Looking for a solution to support ARM iOS Simulators. Does it work if you build on a device? Also, please try to update the native version to the latest one (1.8.4).

Thanks for your patience. Will write here when I have news.

**Comment by ccorneliu** [comment]
Hi @JonathonJulian,

We updated the iOS SDK to version `1.8.5` which supports simulators on your M1 machine. Please run a `pod update Fidel` command from your project's `ios` folder to update to this version.
