### ISSUE TITLE
Fidel dependency not found

### ISSUE THREAD

**Issue by kokiebisu** [FidelLimited/rn-sdk#56]
I have been trying to run the Android emulator using react-native (using expo). I have been getting this error message. 

![Screen Shot 2021-05-04 at 3 07 48 PM](https://user-images.githubusercontent.com/43525282/117076253-f2288a80-acea-11eb-8660-dfc352db2d49.png)

The behaviour seems to vary depending on the environment (some not giving this error) so I'm suspecting it is a problem with the versions.

Current Version
Android Studio Version 4.1.1

**Comment by ccorneliu** [comment]
Hey, @kokiebisu, I will take a look at this in the following days. What type of environments do you have? What are their characteristics?
