### ISSUE TITLE
Warning meta method 'FLSDKOption:' conflicts with same method from another category

### ISSUE THREAD

**Issue by SMJ93** [FidelLimited/rn-sdk#6]
When trying to run [Detox](https://github.com/wix/Detox) to test our app it hangs on the following:

```
ld: warning: meta method 'FLSDKOption:' in category from proj/ios/build/Build/Products/Debug-iphonesimulator/libFidel.a(FLRNOptionsAdapter.o) conflicts with same method from another category
ld: warning: meta method 'FLCountry:' in category from proj/ios/build/Build/Products/Debug-iphonesimulator/libFidel.a(FLRNCountryFromJSAdapter.o) conflicts with same method from another category
```

Detox runs the command:

```
xcodebuild -workspace ../ios/proj.xcworkspace -scheme proj -configuration Debug -sdk iphonesimulator -derivedDataPath ../ios/build
```

Sometimes it just ignores this warning and continues with the build, other times - always with Detox is hangs.

**Comment by c0derabbit** [comment]
@SMJ93 can you please check again with v1.1.0? might have been fixed, 1.1.0 uses the latest versions of the native SDKs

**Comment by SMJ93** [comment]
Hi @c0derabbit, nope I am still seeing it with `1.1.0`

**Comment by c0derabbit** [comment]
thanks, we'll have  a look.
