### ISSUE TITLE
Upgrade to the latest React Native version

### ISSUE THREAD

**Issue by Dirklectisch** [FidelLimited/rn-sdk#76]
The React Native version this package requires (as a peer dependency) is outdated. Version `0.41.2` was released 5 years ago at the time of writing. It's not quite clear to me if it is safe to take on this dependency - React Native is still evolving a lot.

When installing this package into a modern RN application NPM will warn you of the version conflict. It would be great if this package can be updated and tested using a more recent version.

**Comment by cornelfd** [comment]
Hello @Dirklectisch,

Our SDK supports the latest React Native. In your `package.json` you can set the latest RN version. Our library's package.json file, however needs updating, as the latest `npm` does not know how to resolve the `react-native` peer dependency. We have this on our roadmap and we'll solve this issue soon.

So if you'd like to use `npm` to install our library, please use the `--legacy-peer-deps` option: `npm install fidel-react-native --legacy-peer-deps`.

If you'd like to use `yarn`, no need to use any options and you can just install with the following command: `yarn add fidel-react-native`.
